# Site Settings
title: "FamilyTies"  # The title of your website
description: "FamilyTies"  # A short description of your site
url: "https://peruumal.github.io"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave empty unless your site is in a subdirectory

# Author Information
author:
  name: "Perumal"
  email: "m.peruumal@gmail.com"
  github: "peruumak"  # Your GitHub username

# Jekyll Settings
theme: minima  # The theme you're using (e.g., minima, jekyll-theme-cayman)
